// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m3gPohBe9vrDEmv4dw4fmz
// Component: pP7svme3kU
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsjNce8NDoLzVxl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jNce8NDoLzVXL/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: m3gPohBe9vrDEmv4dw4fmz/projectcss
import sty from "./PlasmicDev.module.css"; // plasmic-import: pP7svme3kU/css
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: bGTzanaTDH/icon
import ThreeHorizontalLinesOutlineIcon1Icon from "./icons/PlasmicIcon__ThreeHorizontalLinesOutlineIcon1"; // plasmic-import: 2Vqy-_D6q/icon

export const PlasmicDev__VariantProps = new Array();

export const PlasmicDev__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDev__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjNce8NDoLzVxl()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"webDev"}
              data-plasmic-override={overrides.webDev}
              className={classNames(projectcss.all, sty.webDev)}
            >
              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__glkmk
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Remotely."}
              </p.PlasmicLink>
              {false ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0OkPh
                  )}
                >
                  {"Kickstart your new career with Remotely"}
                </div>
              ) : null}
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__vY0P
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Home"}
              </p.PlasmicLink>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__q60De
                )}
              >
                {"About us"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fLaoo
                )}
              >
                {"FAQS"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3YxC3
                )}
              >
                {"Find your new career"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ncQu8
                )}
              >
                {"Collaborate wth us"}
              </div>
              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eBsuZ
                )}
              >
                {"Apply Now!"}
              </div>
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yapmg
                  )}
                >
                  {
                    "By signing up, you agree to our Terms of Service and Privacy Policy. You will receive offers from Wimdu and agree that we may share your hashed email address with third parties for the purpose of better tailoring advertising to your needs."
                  }
                </div>
                <Line6Icon
                  className={classNames(projectcss.all, sty.svg__oDfm9)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9WQPj
                  )}
                >
                  {
                    "We’ve got the solution: world-class training and development programs developed by top universities and companies."
                  }
                </div>
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___44Hv
                  )}
                >
                  {"Enter email address"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jdnOw
                  )}
                >
                  {"Subscribe"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oArAg
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"companies"}
                  data-plasmic-override={overrides.companies}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rgxEa
                  )}
                >
                  {"Remotely."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lLhlb
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jqAgK
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lk0Gr
                )}
              >
                {"Transform your career with Remotely programs."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rvuB
                )}
              >
                {
                  "Hey there! we are excited to introduce you to our web development and design course, which is designed to teach you everything you need to know to create stunning and functional websites. As you may know, web development are in high demand these days, and learning these skills can open up new opportunities for you, whether you want to start your own business or work as a freelancer.\n\nCourse details:\nOur course covers all the essential topics and skills you need to become a proficient web developer, including HTML, CSS, JavaScript, and more. We’ve created a comprehensive curriculum that includes video lessons, exercises, quizzes, and assignments, so you can learn at your own pace and practice what you've learned.\n\nPricing and payment:\nWe are offering this course at an affordable price of N8500 ($12) per month. You can pay via  direct bank transfer. \n\nTo get access to the paid course material, you'll need to join our WhatsApp group, where you can interact with our supervisor and other students, ask questions, and share your progress. Here's the link to join the group [ https://chat.whatsapp.com/IiRcYiA42y5F2CvmpprBA7]. Please make sure to provide your name and course name when joining the group.\n\nSubmitting proof of payment:\nOnce you've paid for the course, please submit proof of payment via WhatsApp on the group, so we can verify your payment and add you to the paid group. You can use a screenshot of your bank transfer, or any other proof of payment that shows your name and the course name."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zpMda
                )}
              >
                {"Account details"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ieSG
                )}
              >
                {"1700493149"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dh07X
                )}
              >
                {"Providus Bank"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d15Ip
                )}
              >
                {"Esho Babatunde Oladipupo"}
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div
              data-plasmic-name={"webDev2"}
              data-plasmic-override={overrides.webDev2}
              className={classNames(projectcss.all, sty.webDev2)}
            >
              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <ThreeHorizontalLinesOutlineIcon1Icon
                  className={classNames(projectcss.all, sty.svg__jzPIn)}
                  role={"img"}
                />
              ) : null}
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__v8PKr
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Remotely."}
              </p.PlasmicLink>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rjTgZ
                )}
              >
                {"Transform your career with Remotely programs."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lWqQz
                )}
              >
                {
                  "Hey there! we are excited to introduce you to our web development and design course, which is designed to teach you everything you need to know to create stunning and functional websites. As you may know, web development are in high demand these days, and learning these skills can open up new opportunities for you, whether you want to start your own business or work as a freelancer.\n\nCourse details:\nOur course covers all the essential topics and skills you need to become a proficient web developer, including HTML, CSS, JavaScript, and more. We’ve created a comprehensive curriculum that includes video lessons, exercises, quizzes, and assignments, so you can learn at your own pace and practice what you've learned.\n\nPricing and payment:\nWe are offering this course at an affordable price of N8500 ($12) per month. You can pay via  direct bank transfer. \n\nTo get access to the paid course material, you'll need to join our WhatsApp group, where you can interact with our supervisor and other students, ask questions, and share your progress. Here's the link to join the group: [insert WhatsApp group link]. Please make sure to provide your name and course name when joining the group.\n\nSubmitting proof of payment:\nOnce you've paid for the course, please submit proof of payment via WhatsApp on the group, so we can verify your payment and add you to the paid group. You can use a screenshot of your bank transfer, or any other proof of payment that shows your name and the course name."
                }
              </div>
              <div
                data-plasmic-name={"bottom2"}
                data-plasmic-override={overrides.bottom2}
                className={classNames(projectcss.all, sty.bottom2)}
              >
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oN2Hz
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter2"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter2
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter2
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  data-plasmic-name={"companies2"}
                  data-plasmic-override={overrides.companies2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies2
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tjBfb
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__auZl
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__og3Jv
                )}
              >
                {"Account details"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ksDjw
                )}
              >
                {"1700493149"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ihMMd
                )}
              >
                {"Providus Bank"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Iqut
                )}
              >
                {"Esho Babatunde Oladipupo"}
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "webDev",
    "rectangle1",
    "rectangle3",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies",
    "webDev2",
    "rectangle2",
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  webDev: [
    "webDev",
    "rectangle1",
    "rectangle3",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies"
  ],

  rectangle1: ["rectangle1"],
  rectangle3: ["rectangle3"],
  bottom: [
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies"
  ],

  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  followUsFacebookLinkedinTwitter: ["followUsFacebookLinkedinTwitter"],
  companies: ["companies"],
  webDev2: [
    "webDev2",
    "rectangle2",
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle2: ["rectangle2"],
  bottom2: [
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle13: ["rectangle13"],
  followUsFacebookLinkedinTwitter2: ["followUsFacebookLinkedinTwitter2"],
  companies2: ["companies2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDev__ArgProps,
          internalVariantPropNames: PlasmicDev__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDev__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDev";
  } else {
    func.displayName = `PlasmicDev.${nodeName}`;
  }
  return func;
}

export const PlasmicDev = Object.assign(
  // Top-level PlasmicDev renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    webDev: makeNodeComponent("webDev"),
    rectangle1: makeNodeComponent("rectangle1"),
    rectangle3: makeNodeComponent("rectangle3"),
    bottom: makeNodeComponent("bottom"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    followUsFacebookLinkedinTwitter: makeNodeComponent(
      "followUsFacebookLinkedinTwitter"
    ),

    companies: makeNodeComponent("companies"),
    webDev2: makeNodeComponent("webDev2"),
    rectangle2: makeNodeComponent("rectangle2"),
    bottom2: makeNodeComponent("bottom2"),
    rectangle13: makeNodeComponent("rectangle13"),
    followUsFacebookLinkedinTwitter2: makeNodeComponent(
      "followUsFacebookLinkedinTwitter2"
    ),

    companies2: makeNodeComponent("companies2"),
    // Metadata about props expected for PlasmicDev
    internalVariantProps: PlasmicDev__VariantProps,
    internalArgProps: PlasmicDev__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDev;
/* prettier-ignore-end */
