// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m3gPohBe9vrDEmv4dw4fmz
// Component: 294I0ld5JO
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsjNce8NDoLzVxl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jNce8NDoLzVXL/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: m3gPohBe9vrDEmv4dw4fmz/projectcss
import sty from "./PlasmicDesignnn.module.css"; // plasmic-import: 294I0ld5JO/css
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: bGTzanaTDH/icon
import ThreeHorizontalLinesOutlineIcon1Icon from "./icons/PlasmicIcon__ThreeHorizontalLinesOutlineIcon1"; // plasmic-import: 2Vqy-_D6q/icon

export const PlasmicDesignnn__VariantProps = new Array();

export const PlasmicDesignnn__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDesignnn__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjNce8NDoLzVxl()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"webDesign"}
              data-plasmic-override={overrides.webDesign}
              className={classNames(projectcss.all, sty.webDesign)}
            >
              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__vwMsx
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Remotely."}
              </p.PlasmicLink>
              {false ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cdXkV
                  )}
                >
                  {"Kickstart your new career with Remotely"}
                </div>
              ) : null}
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__i8Fvl
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Home"}
              </p.PlasmicLink>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vyLow
                )}
              >
                {"About us"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ueKVz
                )}
              >
                {"FAQS"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u7XtJ
                )}
              >
                {"Find your new career"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__f4Jkx
                )}
              >
                {"Collaborate wth us"}
              </div>
              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__k1Frr
                )}
              >
                {"Apply Now!"}
              </div>
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lh5Mh
                  )}
                >
                  {
                    "By signing up, you agree to our Terms of Service and Privacy Policy. You will receive offers from Wimdu and agree that we may share your hashed email address with third parties for the purpose of better tailoring advertising to your needs."
                  }
                </div>
                <Line6Icon
                  className={classNames(projectcss.all, sty.svg__siRw6)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zsKfX
                  )}
                >
                  {
                    "We’ve got the solution: world-class training and development programs developed by top universities and companies."
                  }
                </div>
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qrP2X
                  )}
                >
                  {"Enter email address"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tr6JG
                  )}
                >
                  {"Subscribe"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mOsqF
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"companies"}
                  data-plasmic-override={overrides.companies}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__krUm3
                  )}
                >
                  {"Remotely."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___30CsI
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wnjzu
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c6Mv8
                )}
              >
                {"Transform your career with Remotely programs."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wL8I
                )}
              >
                {
                  "Hey there! we are excited to introduce you to our web design course, which is designed to teach you everything you need to know to create stunning and functional websites. As you may know, web design are in high demand these days, and learning these skills can open up new opportunities for you, whether you want to start your own business or work as a freelancer.\n\nCourse details:\nOur course covers all the essential topics and skills you need to become a proficient web designer. We’ve created a comprehensive curriculum that includes video lessons, exercises, quizzes, and assignments, so you can learn at your own pace and practice what you've learned.\n\nPricing and payment:\nWe are offering this course at an affordable price of N8500 ($12) per month. You can pay via  direct bank transfer and the course wil span for 3months\n\nTo get access to the paid course material, you'll need to join our WhatsApp group, where you can interact with our supervisor and other students, ask questions, and share your progress. Here's the link to join the group [ https://chat.whatsapp.com/IiRcYiA42y5F2CvmpprBA7]. Please make sure to provide your name and course name when joining the group.\n\nSubmitting proof of payment:\nOnce you've paid for the course, please submit proof of payment via WhatsApp on the group, so we can verify your payment and add you to the paid group. You can use a screenshot of your bank transfer, or any other proof of payment that shows your name and the course name."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nqHoy
                )}
              >
                {"Account details"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vbOyK
                )}
              >
                {"1700493149"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__odJi
                )}
              >
                {"Providus Bank"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fy83X
                )}
              >
                {"Esho Babatunde Oladipupo"}
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div
              data-plasmic-name={"webDes"}
              data-plasmic-override={overrides.webDes}
              className={classNames(projectcss.all, sty.webDes)}
            >
              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <ThreeHorizontalLinesOutlineIcon1Icon
                  className={classNames(projectcss.all, sty.svg__kRl3Q)}
                  role={"img"}
                />
              ) : null}
              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__lu8Q
                )}
                component={Link}
                href={`/`}
                platform={"nextjs"}
              >
                {"Remotely."}
              </p.PlasmicLink>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xUs87
                )}
              >
                {"Transform your career with Remotely programs."}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pGuBn
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "Hey there! we are excited to introduce you to our web  design course, which is designed to teach you everything you need to know to create stunning and functional websites. As you may know, web design are in high demand these days, and learning these skills can open up new opportunities for you, whether you want to start your own business or work as a freelancer.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Course details:"}
                  </span>
                  <React.Fragment>
                    {
                      "\nOur course covers all the essential topics and skills you need to become a proficient web design, We’ve created a comprehensive curriculum that includes video lessons, exercises, quizzes, and assignments, so you can learn at your own pace and practice what you've learned.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Pricing and payment:"}
                  </span>
                  <React.Fragment>
                    {
                      "\nWe are offering this course at an affordable price of N8500 ($12) per month. You can pay via  direct bank transfer and the course wil span for 3months \n\nTo get access to the paid course material, you'll need to join our WhatsApp group, where you can interact with our supervisor and other students, ask questions, and share your progress. Here's the link to join the group: [insert WhatsApp group link]. Please make sure to provide your name and course name when joining the group.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Submitting proof of payment:"}
                  </span>
                  <React.Fragment>
                    {
                      "\nOnce you've paid for the course, please submit proof of payment via WhatsApp on the group, so we can verify your payment and add you to the paid group. You can use a screenshot of your bank transfer, or any other proof of payment that shows your name and the course name."
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
              <div
                data-plasmic-name={"bottom2"}
                data-plasmic-override={overrides.bottom2}
                className={classNames(projectcss.all, sty.bottom2)}
              >
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gQtRe
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter2"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter2
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter2
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  data-plasmic-name={"companies2"}
                  data-plasmic-override={overrides.companies2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies2
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___07Nau
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vHehD
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ujIlE
                )}
              >
                {"Account details"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h1AMw
                )}
              >
                {"1700493149"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tJx1G
                )}
              >
                {"Providus Bank"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mogU
                )}
              >
                {"Esho Babatunde Oladipupo"}
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "webDesign",
    "rectangle1",
    "rectangle3",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies",
    "webDes",
    "rectangle2",
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  webDesign: [
    "webDesign",
    "rectangle1",
    "rectangle3",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies"
  ],

  rectangle1: ["rectangle1"],
  rectangle3: ["rectangle3"],
  bottom: [
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies"
  ],

  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  followUsFacebookLinkedinTwitter: ["followUsFacebookLinkedinTwitter"],
  companies: ["companies"],
  webDes: [
    "webDes",
    "rectangle2",
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle2: ["rectangle2"],
  bottom2: [
    "bottom2",
    "rectangle13",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle13: ["rectangle13"],
  followUsFacebookLinkedinTwitter2: ["followUsFacebookLinkedinTwitter2"],
  companies2: ["companies2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDesignnn__ArgProps,
          internalVariantPropNames: PlasmicDesignnn__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDesignnn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDesignnn";
  } else {
    func.displayName = `PlasmicDesignnn.${nodeName}`;
  }
  return func;
}

export const PlasmicDesignnn = Object.assign(
  // Top-level PlasmicDesignnn renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    webDesign: makeNodeComponent("webDesign"),
    rectangle1: makeNodeComponent("rectangle1"),
    rectangle3: makeNodeComponent("rectangle3"),
    bottom: makeNodeComponent("bottom"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    followUsFacebookLinkedinTwitter: makeNodeComponent(
      "followUsFacebookLinkedinTwitter"
    ),

    companies: makeNodeComponent("companies"),
    webDes: makeNodeComponent("webDes"),
    rectangle2: makeNodeComponent("rectangle2"),
    bottom2: makeNodeComponent("bottom2"),
    rectangle13: makeNodeComponent("rectangle13"),
    followUsFacebookLinkedinTwitter2: makeNodeComponent(
      "followUsFacebookLinkedinTwitter2"
    ),

    companies2: makeNodeComponent("companies2"),
    // Metadata about props expected for PlasmicDesignnn
    internalVariantProps: PlasmicDesignnn__VariantProps,
    internalArgProps: PlasmicDesignnn__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDesignnn;
/* prettier-ignore-end */
