// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m3gPohBe9vrDEmv4dw4fmz
// Component: CAPbTLfcIgX6
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import { useScreenVariants as useScreenVariantsjNce8NDoLzVxl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: jNce8NDoLzVXL/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: m3gPohBe9vrDEmv4dw4fmz/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: CAPbTLfcIgX6/css
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: HGg_RpF-pa/icon
import Line6Icon from "./icons/PlasmicIcon__Line6"; // plasmic-import: bGTzanaTDH/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: vv0Z8snRT/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjNce8NDoLzVxl()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
          ) ? (
            <div
              data-plasmic-name={"homePage"}
              data-plasmic-override={overrides.homePage}
              className={classNames(projectcss.all, sty.homePage)}
            >
              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />

              <p.PlasmicLink
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                platform={"nextjs"}
              >
                {"Remotely."}
              </p.PlasmicLink>
              {false ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4D28O
                  )}
                >
                  {"Kickstart your new career with Remotely"}
                </div>
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___01Td5
                )}
              >
                {"Home"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0AKoX
                )}
              >
                {"About us"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__twrtC
                )}
              >
                {"FAQS"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mRlrv
                )}
              >
                {"Find your new career"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qao6D
                )}
              >
                {"Collaborate wth us"}
              </div>
              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(projectcss.all, sty.rectangle3)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c82Ke
                )}
              >
                {"Apply Now!"}
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"maskGroup"}
                  data-plasmic-override={overrides.maskGroup}
                  className={classNames(projectcss.all, sty.maskGroup)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"_16751036812281"}
                      data-plasmic-override={overrides._16751036812281}
                      className={classNames(
                        projectcss.all,
                        sty._16751036812281
                      )}
                    />
                  ) : null}
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={
                    "highQualityProjectBasedEducationForEveryone"
                  }
                  data-plasmic-override={
                    overrides.highQualityProjectBasedEducationForEveryone
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.highQualityProjectBasedEducationForEveryone
                  )}
                >
                  {"High-quality Project\nBased Education For Everyone. "}
                </div>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__m5LAa
                  )}
                >
                  {
                    "At Remotely, our mission is to power pupil engagement and fulfillment via actual-global venture-primarily based studying. We provide instructors with the tools they need to put into effect superb PBL that builds destiny-ready talents."
                  }
                </div>
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lyMeW
                )}
              >
                {
                  "Remotely isn't like the conventional establishments. We're a school for people seeking to benefit technical capabilities and kickstart a new career. Remotely takes a non-conventional approach to studying via coaching guides directly linked with the selected tune."
                }
              </div>
              <div
                data-plasmic-name={"joinUsNow"}
                data-plasmic-override={overrides.joinUsNow}
                className={classNames(projectcss.all, sty.joinUsNow)}
              >
                <div
                  data-plasmic-name={"rectangle4"}
                  data-plasmic-override={overrides.rectangle4}
                  className={classNames(projectcss.all, sty.rectangle4)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__auDrG
                  )}
                >
                  {"Join us now!"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nQLy
                )}
              >
                {"WHAT IS REMOTELY ?"}
              </div>
              <div
                data-plasmic-name={"_2ndPicture"}
                data-plasmic-override={overrides._2ndPicture}
                className={classNames(projectcss.all, sty._2ndPicture)}
              >
                <div
                  data-plasmic-name={"_16751153945451"}
                  data-plasmic-override={overrides._16751153945451}
                  className={classNames(projectcss.all, sty._16751153945451)}
                />
              </div>
              <Ellipse2Icon
                className={classNames(projectcss.all, sty.svg__daqK)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle5"}
                data-plasmic-override={overrides.rectangle5}
                className={classNames(projectcss.all, sty.rectangle5)}
              />

              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(projectcss.all, sty.rectangle6)}
              />

              <p.PlasmicLink
                data-plasmic-name={"dataScience"}
                data-plasmic-override={overrides.dataScience}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.dataScience
                )}
                component={Link}
                href={`/new-page-2`}
                platform={"nextjs"}
                target={undefined}
              >
                <div
                  data-plasmic-name={"rectangle7"}
                  data-plasmic-override={overrides.rectangle7}
                  className={classNames(projectcss.all, sty.rectangle7)}
                />

                <div
                  data-plasmic-name={"maskGroup2"}
                  data-plasmic-override={overrides.maskGroup2}
                  className={classNames(projectcss.all, sty.maskGroup2)}
                >
                  <div
                    data-plasmic-name={"_1675193663649"}
                    data-plasmic-override={overrides._1675193663649}
                    className={classNames(projectcss.all, sty._1675193663649)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dti8Y
                  )}
                >
                  {"UIUX"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9Kiqy
                  )}
                >
                  {
                    "This covers all aspects of product\ndevelopment including design, usability, function and more."
                  }
                </div>
              </p.PlasmicLink>
              <p.PlasmicLink
                data-plasmic-name={"fullStack"}
                data-plasmic-override={overrides.fullStack}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.fullStack
                )}
                component={Link}
                href={`/new-page`}
                platform={"nextjs"}
              >
                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(projectcss.all, sty.rectangle8)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ksSlO
                    )}
                  >
                    {"Full Stack Development"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"maskGroup3"}
                  data-plasmic-override={overrides.maskGroup3}
                  className={classNames(projectcss.all, sty.maskGroup3)}
                >
                  <div
                    data-plasmic-name={"_1677017186319"}
                    data-plasmic-override={overrides._1677017186319}
                    className={classNames(projectcss.all, sty._1677017186319)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nMy3I
                  )}
                >
                  {
                    "This covers a wide range of technologies and programming language, such as HTML, CSS, JAVASCRIPT and many more."
                  }
                </div>
              </p.PlasmicLink>
              <div
                data-plasmic-name={"dataScience2"}
                data-plasmic-override={overrides.dataScience2}
                className={classNames(projectcss.all, sty.dataScience2)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  data-plasmic-name={"maskGroup4"}
                  data-plasmic-override={overrides.maskGroup4}
                  className={classNames(projectcss.all, sty.maskGroup4)}
                >
                  <div
                    data-plasmic-name={"_1677017186412"}
                    data-plasmic-override={overrides._1677017186412}
                    className={classNames(projectcss.all, sty._1677017186412)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uhTh2
                  )}
                >
                  {"Software Develpoment"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jYpju
                  )}
                >
                  {
                    "This involves the use of various programming languages, tools and methodologies to develop software that meets the requirements of the end-users."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"bottom"}
                data-plasmic-override={overrides.bottom}
                className={classNames(projectcss.all, sty.bottom)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bkyXv
                  )}
                >
                  {
                    "By signing up, you agree to our Terms of Service and Privacy Policy. You will receive offers from Wimdu and agree that we may share your hashed email address with third parties for the purpose of better tailoring advertising to your needs."
                  }
                </div>
                <Line6Icon
                  className={classNames(projectcss.all, sty.svg__c52Ps)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dp6Jy
                  )}
                >
                  {
                    "We’ve got the solution: world-class training and development programs developed by top universities and companies."
                  }
                </div>
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["setVariable"] = true
                      ? (() => {
                          const actionArgs = {};
                          return __wrapUserFunction(
                            {
                              type: "InteractionLoc",
                              actionName: "updateVariable",
                              interactionUuid: "DLPia_rjQ",
                              componentUuid: "CAPbTLfcIgX6"
                            },
                            () =>
                              (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                const { objRoot, variablePath } = variable;
                                undefined;
                              })?.apply(null, [actionArgs]),
                            actionArgs
                          );
                        })()
                      : undefined;
                    if (
                      typeof $steps["setVariable"] === "object" &&
                      typeof $steps["setVariable"].then === "function"
                    ) {
                      $steps["setVariable"] = await __wrapUserPromise(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "DLPia_rjQ",
                          componentUuid: "CAPbTLfcIgX6"
                        },
                        $steps["setVariable"]
                      );
                    }
                  }}
                />

                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kk3DR
                  )}
                >
                  {"Enter email address"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__igQqG
                  )}
                >
                  {"Subscribe"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wtiv4
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"companies"}
                  data-plasmic-override={overrides.companies}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xNTY
                  )}
                >
                  {"Remotely."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ndkKk
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tMcYk
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__h9Wsy
                )}
              >
                {"Contact Us"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___98YrU
                )}
              >
                {
                  "Whether you're looking for supplementary materials or a modern approach to project-based learning, Remotely is here to assist. Tap underneath to contact us"
                }
              </div>
              <div
                data-plasmic-name={"rectangle13"}
                data-plasmic-override={overrides.rectangle13}
                className={classNames(projectcss.all, sty.rectangle13)}
              />

              <div
                data-plasmic-name={"learnMore"}
                data-plasmic-override={overrides.learnMore}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.learnMore
                )}
              >
                {"+234 905 238 1693"}
              </div>
            </div>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "mobileOnly") ? true : false
          ) ? (
            <div
              data-plasmic-name={"iPhone14ProMax1"}
              data-plasmic-override={overrides.iPhone14ProMax1}
              className={classNames(projectcss.all, sty.iPhone14ProMax1)}
            >
              <div
                data-plasmic-name={"rectangle2"}
                data-plasmic-override={overrides.rectangle2}
                className={classNames(projectcss.all, sty.rectangle2)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aTse
                )}
              >
                {"Remotely."}
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__e0JcG)}
                  triggerOnce={true}
                >
                  <div
                    data-plasmic-name={
                      "highQualityProjectBasedEducationForEveryone2"
                    }
                    data-plasmic-override={
                      overrides.highQualityProjectBasedEducationForEveryone2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.highQualityProjectBasedEducationForEveryone2
                    )}
                  >
                    {"High-quality Project\nBased Education For\nEveryone. "}
                  </div>
                </Reveal>
              ) : null}
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__ciAce)}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d5Beq
                    )}
                  >
                    {
                      "At Remotely, our mission is to power pupil engagement and fulfillment via actual-global venture-primarily based studying. We provide instructors with the tools they need to put into effect superb PBL that builds destiny-ready talents."
                    }
                  </div>
                </Reveal>
              ) : null}
              <div
                data-plasmic-name={"maskGroup5"}
                data-plasmic-override={overrides.maskGroup5}
                className={classNames(projectcss.all, sty.maskGroup5)}
              >
                <div
                  data-plasmic-name={"_16751036812282"}
                  data-plasmic-override={overrides._16751036812282}
                  className={classNames(projectcss.all, sty._16751036812282)}
                />
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__gYad1)}
                  role={"img"}
                />
              ) : null}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uKq3S
                )}
              >
                {"What is Remotely?"}
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__xwmbh)}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d4X5C
                    )}
                  >
                    {
                      "Remotely isn't like the conventional establishments. We're a school for people seeking to benefit technical capabilities and kickstart a new career. Remotely takes a non-conventional approach to studying via coaching guides directly linked with the selected tune."
                    }
                  </div>
                </Reveal>
              ) : null}
              <div
                data-plasmic-name={"_2ndPicture2"}
                data-plasmic-override={overrides._2ndPicture2}
                className={classNames(projectcss.all, sty._2ndPicture2)}
              >
                <div
                  data-plasmic-name={"_16751153945452"}
                  data-plasmic-override={overrides._16751153945452}
                  className={classNames(projectcss.all, sty._16751153945452)}
                />
              </div>
              <div
                data-plasmic-name={"rectangle14"}
                data-plasmic-override={overrides.rectangle14}
                className={classNames(projectcss.all, sty.rectangle14)}
              />

              <div
                data-plasmic-name={"rectangle15"}
                data-plasmic-override={overrides.rectangle15}
                className={classNames(projectcss.all, sty.rectangle15)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u6Aa2
                )}
              >
                {"Explore our courses"}
              </div>
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <Reveal
                  className={classNames("__wab_instance", sty.reveal___52YJu)}
                  triggerOnce={true}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <p.PlasmicLink
                      data-plasmic-name={"dataScience3"}
                      data-plasmic-override={overrides.dataScience3}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.dataScience3
                      )}
                      component={Link}
                      href={`/new-page-2`}
                      platform={"nextjs"}
                    >
                      <div
                        data-plasmic-name={"rectangle16"}
                        data-plasmic-override={overrides.rectangle16}
                        className={classNames(projectcss.all, sty.rectangle16)}
                      />

                      <div
                        data-plasmic-name={"maskGroup6"}
                        data-plasmic-override={overrides.maskGroup6}
                        className={classNames(projectcss.all, sty.maskGroup6)}
                      >
                        <div
                          data-plasmic-name={"_1675193663650"}
                          data-plasmic-override={overrides._1675193663650}
                          className={classNames(
                            projectcss.all,
                            sty._1675193663650
                          )}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mUc99
                        )}
                      >
                        {"UIUX"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jdg8T
                        )}
                      >
                        {
                          "This covers all aspects of product\ndevelopment including design, usability, function and more."
                        }
                      </div>
                    </p.PlasmicLink>
                  ) : null}
                </Reveal>
              ) : null}
              <p.PlasmicLink
                data-plasmic-name={"fullStack2"}
                data-plasmic-override={overrides.fullStack2}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.fullStack2
                )}
                component={Link}
                href={`/new-page`}
                platform={"nextjs"}
              >
                <div
                  data-plasmic-name={"rectangle17"}
                  data-plasmic-override={overrides.rectangle17}
                  className={classNames(projectcss.all, sty.rectangle17)}
                />

                <div
                  data-plasmic-name={"maskGroup7"}
                  data-plasmic-override={overrides.maskGroup7}
                  className={classNames(projectcss.all, sty.maskGroup7)}
                >
                  <div
                    data-plasmic-name={"_1677017186320"}
                    data-plasmic-override={overrides._1677017186320}
                    className={classNames(projectcss.all, sty._1677017186320)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7OcPb
                  )}
                >
                  {"Full Stack Development"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yU45D
                  )}
                >
                  {
                    "This covers a wide range of technologies and programming language, such as HTML, CSS, JAVASCRIPT and many more."
                  }
                </div>
              </p.PlasmicLink>
              <div
                data-plasmic-name={"dataScience4"}
                data-plasmic-override={overrides.dataScience4}
                className={classNames(projectcss.all, sty.dataScience4)}
              >
                <div
                  data-plasmic-name={"rectangle18"}
                  data-plasmic-override={overrides.rectangle18}
                  className={classNames(projectcss.all, sty.rectangle18)}
                />

                <div
                  data-plasmic-name={"maskGroup8"}
                  data-plasmic-override={overrides.maskGroup8}
                  className={classNames(projectcss.all, sty.maskGroup8)}
                >
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : true
                  ) ? (
                    <div
                      data-plasmic-name={"_1675193663589"}
                      data-plasmic-override={overrides._1675193663589}
                      className={classNames(projectcss.all, sty._1675193663589)}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"_1677017186413"}
                    data-plasmic-override={overrides._1677017186413}
                    className={classNames(projectcss.all, sty._1677017186413)}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dJuQf
                  )}
                >
                  {"Software Develpoment"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qilRy
                  )}
                >
                  {
                    "This involves the use of various programming languages, tools and methodologies to develop software that meets the requirements of the end-users."
                  }
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___20G01
                )}
              >
                {"Contact Us"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p8N11
                )}
              >
                {
                  "Whether you're looking for supplementary materials or a modern approach to project-based learning, Remotely is here to assist. Tap underneath to contact us"
                }
              </div>
              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(projectcss.all, sty.rectangle19)}
              />

              <div
                data-plasmic-name={"learnMore2"}
                data-plasmic-override={overrides.learnMore2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.learnMore2
                )}
              >
                {"+234 905 238 1693"}
              </div>
              <div
                data-plasmic-name={"bottom2"}
                data-plasmic-override={overrides.bottom2}
                className={classNames(projectcss.all, sty.bottom2)}
              >
                <div
                  data-plasmic-name={"rectangle20"}
                  data-plasmic-override={overrides.rectangle20}
                  className={classNames(projectcss.all, sty.rectangle20)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6FajW
                  )}
                >
                  {"About us\n\r\n\nOur Story\n\nBlog"}
                </div>
                <div
                  data-plasmic-name={"followUsFacebookLinkedinTwitter2"}
                  data-plasmic-override={
                    overrides.followUsFacebookLinkedinTwitter2
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.followUsFacebookLinkedinTwitter2
                  )}
                >
                  {"Follow us\r\n\nFacebook\r\n\r\nLinkedin\r\n\nTwitter\r\n"}
                </div>
                <div
                  data-plasmic-name={"companies2"}
                  data-plasmic-override={overrides.companies2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.companies2
                  )}
                >
                  {"Companies\n"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__upUHr
                  )}
                >
                  {"Collaborate with us"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pxv3F
                  )}
                >
                  {"Find your new career"}
                </div>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "homePage",
    "rectangle1",
    "link",
    "rectangle3",
    "maskGroup",
    "_16751036812281",
    "highQualityProjectBasedEducationForEveryone",
    "joinUsNow",
    "rectangle4",
    "_2ndPicture",
    "_16751153945451",
    "rectangle5",
    "rectangle6",
    "dataScience",
    "rectangle7",
    "maskGroup2",
    "_1675193663649",
    "fullStack",
    "rectangle8",
    "maskGroup3",
    "_1677017186319",
    "dataScience2",
    "rectangle9",
    "maskGroup4",
    "_1677017186412",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies",
    "rectangle13",
    "learnMore",
    "iPhone14ProMax1",
    "rectangle2",
    "highQualityProjectBasedEducationForEveryone2",
    "maskGroup5",
    "_16751036812282",
    "_2ndPicture2",
    "_16751153945452",
    "rectangle14",
    "rectangle15",
    "dataScience3",
    "rectangle16",
    "maskGroup6",
    "_1675193663650",
    "fullStack2",
    "rectangle17",
    "maskGroup7",
    "_1677017186320",
    "dataScience4",
    "rectangle18",
    "maskGroup8",
    "_1675193663589",
    "_1677017186413",
    "rectangle19",
    "learnMore2",
    "bottom2",
    "rectangle20",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  homePage: [
    "homePage",
    "rectangle1",
    "link",
    "rectangle3",
    "maskGroup",
    "_16751036812281",
    "highQualityProjectBasedEducationForEveryone",
    "joinUsNow",
    "rectangle4",
    "_2ndPicture",
    "_16751153945451",
    "rectangle5",
    "rectangle6",
    "dataScience",
    "rectangle7",
    "maskGroup2",
    "_1675193663649",
    "fullStack",
    "rectangle8",
    "maskGroup3",
    "_1677017186319",
    "dataScience2",
    "rectangle9",
    "maskGroup4",
    "_1677017186412",
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies",
    "rectangle13",
    "learnMore"
  ],

  rectangle1: ["rectangle1"],
  link: ["link"],
  rectangle3: ["rectangle3"],
  maskGroup: ["maskGroup", "_16751036812281"],
  _16751036812281: ["_16751036812281"],
  highQualityProjectBasedEducationForEveryone: [
    "highQualityProjectBasedEducationForEveryone"
  ],

  joinUsNow: ["joinUsNow", "rectangle4"],
  rectangle4: ["rectangle4"],
  _2ndPicture: ["_2ndPicture", "_16751153945451"],
  _16751153945451: ["_16751153945451"],
  rectangle5: ["rectangle5"],
  rectangle6: ["rectangle6"],
  dataScience: ["dataScience", "rectangle7", "maskGroup2", "_1675193663649"],
  rectangle7: ["rectangle7"],
  maskGroup2: ["maskGroup2", "_1675193663649"],
  _1675193663649: ["_1675193663649"],
  fullStack: ["fullStack", "rectangle8", "maskGroup3", "_1677017186319"],
  rectangle8: ["rectangle8"],
  maskGroup3: ["maskGroup3", "_1677017186319"],
  _1677017186319: ["_1677017186319"],
  dataScience2: ["dataScience2", "rectangle9", "maskGroup4", "_1677017186412"],
  rectangle9: ["rectangle9"],
  maskGroup4: ["maskGroup4", "_1677017186412"],
  _1677017186412: ["_1677017186412"],
  bottom: [
    "bottom",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "followUsFacebookLinkedinTwitter",
    "companies"
  ],

  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  followUsFacebookLinkedinTwitter: ["followUsFacebookLinkedinTwitter"],
  companies: ["companies"],
  rectangle13: ["rectangle13"],
  learnMore: ["learnMore"],
  iPhone14ProMax1: [
    "iPhone14ProMax1",
    "rectangle2",
    "highQualityProjectBasedEducationForEveryone2",
    "maskGroup5",
    "_16751036812282",
    "_2ndPicture2",
    "_16751153945452",
    "rectangle14",
    "rectangle15",
    "dataScience3",
    "rectangle16",
    "maskGroup6",
    "_1675193663650",
    "fullStack2",
    "rectangle17",
    "maskGroup7",
    "_1677017186320",
    "dataScience4",
    "rectangle18",
    "maskGroup8",
    "_1675193663589",
    "_1677017186413",
    "rectangle19",
    "learnMore2",
    "bottom2",
    "rectangle20",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle2: ["rectangle2"],
  highQualityProjectBasedEducationForEveryone2: [
    "highQualityProjectBasedEducationForEveryone2"
  ],

  maskGroup5: ["maskGroup5", "_16751036812282"],
  _16751036812282: ["_16751036812282"],
  _2ndPicture2: ["_2ndPicture2", "_16751153945452"],
  _16751153945452: ["_16751153945452"],
  rectangle14: ["rectangle14"],
  rectangle15: ["rectangle15"],
  dataScience3: ["dataScience3", "rectangle16", "maskGroup6", "_1675193663650"],
  rectangle16: ["rectangle16"],
  maskGroup6: ["maskGroup6", "_1675193663650"],
  _1675193663650: ["_1675193663650"],
  fullStack2: ["fullStack2", "rectangle17", "maskGroup7", "_1677017186320"],
  rectangle17: ["rectangle17"],
  maskGroup7: ["maskGroup7", "_1677017186320"],
  _1677017186320: ["_1677017186320"],
  dataScience4: [
    "dataScience4",
    "rectangle18",
    "maskGroup8",
    "_1675193663589",
    "_1677017186413"
  ],

  rectangle18: ["rectangle18"],
  maskGroup8: ["maskGroup8", "_1675193663589", "_1677017186413"],
  _1675193663589: ["_1675193663589"],
  _1677017186413: ["_1677017186413"],
  rectangle19: ["rectangle19"],
  learnMore2: ["learnMore2"],
  bottom2: [
    "bottom2",
    "rectangle20",
    "followUsFacebookLinkedinTwitter2",
    "companies2"
  ],

  rectangle20: ["rectangle20"],
  followUsFacebookLinkedinTwitter2: ["followUsFacebookLinkedinTwitter2"],
  companies2: ["companies2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    homePage: makeNodeComponent("homePage"),
    rectangle1: makeNodeComponent("rectangle1"),
    link: makeNodeComponent("link"),
    rectangle3: makeNodeComponent("rectangle3"),
    maskGroup: makeNodeComponent("maskGroup"),
    _16751036812281: makeNodeComponent("_16751036812281"),
    highQualityProjectBasedEducationForEveryone: makeNodeComponent(
      "highQualityProjectBasedEducationForEveryone"
    ),

    joinUsNow: makeNodeComponent("joinUsNow"),
    rectangle4: makeNodeComponent("rectangle4"),
    _2ndPicture: makeNodeComponent("_2ndPicture"),
    _16751153945451: makeNodeComponent("_16751153945451"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle6: makeNodeComponent("rectangle6"),
    dataScience: makeNodeComponent("dataScience"),
    rectangle7: makeNodeComponent("rectangle7"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    _1675193663649: makeNodeComponent("_1675193663649"),
    fullStack: makeNodeComponent("fullStack"),
    rectangle8: makeNodeComponent("rectangle8"),
    maskGroup3: makeNodeComponent("maskGroup3"),
    _1677017186319: makeNodeComponent("_1677017186319"),
    dataScience2: makeNodeComponent("dataScience2"),
    rectangle9: makeNodeComponent("rectangle9"),
    maskGroup4: makeNodeComponent("maskGroup4"),
    _1677017186412: makeNodeComponent("_1677017186412"),
    bottom: makeNodeComponent("bottom"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    followUsFacebookLinkedinTwitter: makeNodeComponent(
      "followUsFacebookLinkedinTwitter"
    ),

    companies: makeNodeComponent("companies"),
    rectangle13: makeNodeComponent("rectangle13"),
    learnMore: makeNodeComponent("learnMore"),
    iPhone14ProMax1: makeNodeComponent("iPhone14ProMax1"),
    rectangle2: makeNodeComponent("rectangle2"),
    highQualityProjectBasedEducationForEveryone2: makeNodeComponent(
      "highQualityProjectBasedEducationForEveryone2"
    ),

    maskGroup5: makeNodeComponent("maskGroup5"),
    _16751036812282: makeNodeComponent("_16751036812282"),
    _2ndPicture2: makeNodeComponent("_2ndPicture2"),
    _16751153945452: makeNodeComponent("_16751153945452"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle15: makeNodeComponent("rectangle15"),
    dataScience3: makeNodeComponent("dataScience3"),
    rectangle16: makeNodeComponent("rectangle16"),
    maskGroup6: makeNodeComponent("maskGroup6"),
    _1675193663650: makeNodeComponent("_1675193663650"),
    fullStack2: makeNodeComponent("fullStack2"),
    rectangle17: makeNodeComponent("rectangle17"),
    maskGroup7: makeNodeComponent("maskGroup7"),
    _1677017186320: makeNodeComponent("_1677017186320"),
    dataScience4: makeNodeComponent("dataScience4"),
    rectangle18: makeNodeComponent("rectangle18"),
    maskGroup8: makeNodeComponent("maskGroup8"),
    _1675193663589: makeNodeComponent("_1675193663589"),
    _1677017186413: makeNodeComponent("_1677017186413"),
    rectangle19: makeNodeComponent("rectangle19"),
    learnMore2: makeNodeComponent("learnMore2"),
    bottom2: makeNodeComponent("bottom2"),
    rectangle20: makeNodeComponent("rectangle20"),
    followUsFacebookLinkedinTwitter2: makeNodeComponent(
      "followUsFacebookLinkedinTwitter2"
    ),

    companies2: makeNodeComponent("companies2"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
